### ISSUE TITLE
프로젝트 생성 및 세팅

### ISSUE THREAD

**Issue by TTOzzi** [depromeet/Archive_iOS#2]
## Task
- 프로젝트 생성 및 설정
- Carthage로 사용할 서드파티 설치

**Comment by TTOzzi** [comment]
안녕하세요! @HanweeeeLee님!
늦은시간에 멘션 죄송함다 🙇 
Carthage로 종속성 설치하는데 벌써부터 문제가 많네요.. 😭 

<img width="1006" alt="스크린샷 2021-10-01 오전 12 37 36" src="https://user-images.githubusercontent.com/50410213/135486692-ec694fec-f8e7-4a9e-a195-626eada5f71f.png">

https://github.com/Carthage/Carthage/pull/1945
https://github.com/Moya/Moya/issues/2165

그냥 무난무난하게 Pod이나 SPM으로 가는건 어떨까요?!

**Comment by HanweeeeLee** [comment]
좋습니다! @TTOzzi 님!
저는 pod, SPM 둘중 아무거나 상관이 없어서..
편하신걸로 하시면 될것같습니다 ! (섞어써도 상관 없어요 !)
